services:
  pilotschoolcheckin:
    image: pilotschoolcheckin
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=derevo165;Pooling=false;Host=db;Port=5432;Database=Pilot_School_CheckIn
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: myapp-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=derevo165
      - POSTGRES_DB=Pilot_School_CheckIn
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: